In [233]:
import numpy as np
from IPython.display import IFrame
from collections import namedtuple
from itertools import product
import random

In [297]:
np.set_printoptions(linewidth=150, nanstr='')

# Grid Puzzle Solver

This is an attempt to solve a math puzzle, found at the May 2019 edition of [Monroe Community College Math website](https://sites.monroecc.edu/mathpuzzler/2019/05/01/may-2019-puzzle).  I was inspired to try it out after seeing this

In [7]:
## Make Puzzle

The Puzzle itself is:

![](https://sites.monroecc.edu/mathpuzzler/files/2019/04/May19Grid.gif)

I'll use Nones and integers to represent it in Python

In [298]:
def build_puzzle():
    _ = None
    return np.array(
        (
        (_, _, 9, _, _, 2, _, 6, _, _, _, _, _, _, 8, _, _, _, _, _),
        (_, _, _, _, _, _, _, _, _, _, _, _, 8, _, _, _, _, 6, _, _),
        (_, _, _, _, 6, _, _, _, _, _, 7, _, _, _, _, _, _, _, _, _),
        (6, _, _, _, _, _, _, 6, _, _, _, _, _, _, _, _, 6, _, _, 4),
        (_, _, _, _, _, _, _, _, _, _, 9, _, _,12, _, _, _, _, 2, _),
        (_, _, _, _, _,12, _, 4, _, _, _, _, _, _, _, 8, _, _, _, _),
        (_, _, 6, _, _, _, _, _, _, 6, _, _, _, _, 4, _, _, _, _, 4),
        (_, _, _, _, _, _, _, _, _, _, _,12, _, _, _, _, 2, _, _, _),
        (_, _, _, _, _, _, 6, _, _, _, _, _, _, _, 6, _, _, _, 8, _),
        (6, _, _, _, 9, _, _, _, 6, _, _, _, _, _, _, _, 4, _, _, _),
        ),
    dtype=float)

puzzle = build_puzzle()
puzzle

array([[   ,    ,  9.,    ,    ,  2.,    ,  6.,    ,    ,    ,    ,    ,    ,  8.,    ,    ,    ,    ,    ],
       [   ,    ,    ,    ,    ,    ,    ,    ,    ,    ,    ,    ,  8.,    ,    ,    ,    ,  6.,    ,    ],
       [   ,    ,    ,    ,  6.,    ,    ,    ,    ,    ,  7.,    ,    ,    ,    ,    ,    ,    ,    ,    ],
       [ 6.,    ,    ,    ,    ,    ,    ,  6.,    ,    ,    ,    ,    ,    ,    ,    ,  6.,    ,    ,  4.],
       [   ,    ,    ,    ,    ,    ,    ,    ,    ,    ,  9.,    ,    , 12.,    ,    ,    ,    ,  2.,    ],
       [   ,    ,    ,    ,    , 12.,    ,  4.,    ,    ,    ,    ,    ,    ,    ,  8.,    ,    ,    ,    ],
       [   ,    ,  6.,    ,    ,    ,    ,    ,    ,  6.,    ,    ,    ,    ,  4.,    ,    ,    ,    ,  4.],
       [   ,    ,    ,    ,    ,    ,    ,    ,    ,    ,    , 12.,    ,    ,    ,    ,  2.,    ,    ,    ],
       [   ,    ,    ,    ,    ,    ,  6.,    ,    ,    ,    ,    ,    ,    ,  6.,    ,    ,    ,  8.,    ],
       [ 6.,    ,  

Let's also list the coordinates of each clue in order to start searching for rectangles

In [36]:
puzzle[puzzle > 0]

C:\Users\NickDG\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([ 9.,  2.,  6.,  8.,  8.,  6.,  6.,  7.,  6.,  6.,  6.,  4.,  9.,
       12.,  2., 12.,  4.,  8.,  6.,  6.,  4.,  4., 12.,  2.,  6.,  6.,
        8.,  6.,  9.,  6.,  4.])

In [41]:
hint_coords = list(zip(*np.where(puzzle > 0)))
print(hint_coords)

[(0, 2), (0, 5), (0, 7), (0, 14), (1, 12), (1, 17), (2, 4), (2, 10), (3, 0), (3, 7), (3, 16), (3, 19), (4, 10), (4, 13), (4, 18), (5, 5), (5, 7), (5, 15), (6, 2), (6, 9), (6, 14), (6, 19), (7, 11), (7, 16), (8, 6), (8, 14), (8, 18), (9, 0), (9, 4), (9, 8), (9, 16)]


C:\Users\NickDG\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


Let's also list all possible coordinates for the puzzle:

In [46]:
coords = tuple(product(list(range(len(puzzle))), list(range(len(puzzle[0])))))
print(coords)

((0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16), (2, 17), (2, 18), (2, 19), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15), (3, 16), (3, 17), (3, 18), (3, 19), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (4, 12), (4, 13), (4, 14), (4, 15), (4, 16), (4, 17), (4, 18), (4, 19), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11), (5, 12), (5, 13), (5, 14), (5, 15), (5, 16), (5, 17

Finally, let's give each coordinate a space to put each possible rectangle that may fall into it.  Whenever the possible list goes down to one, then we know it's correct.

{(0, 2): [],
 (0, 5): [],
 (0, 7): [],
 (0, 14): [],
 (1, 12): [],
 (1, 17): [],
 (2, 4): [],
 (2, 10): [],
 (3, 0): [],
 (3, 7): [],
 (3, 16): [],
 (3, 19): [],
 (4, 10): [],
 (4, 13): [],
 (4, 18): [],
 (5, 5): [],
 (5, 7): [],
 (5, 15): [],
 (6, 2): [],
 (6, 9): [],
 (6, 14): [],
 (6, 19): [],
 (7, 11): [],
 (7, 16): [],
 (8, 6): [],
 (8, 14): [],
 (8, 18): [],
 (9, 0): [],
 (9, 4): [],
 (9, 8): [],
 (9, 16): []}

## Put in all possible rectangles of size *Hint*
Well, we know how big each rectangle can be, so let's just put it in with all offsets.  Should be a lot of them.

In [49]:
set(hints)

{2.0, 4.0, 6.0, 7.0, 8.0, 9.0, 12.0}

In [57]:
rects = {
    2: [(2, 1), (1, 2)],
    4: [(4, 1), (2, 2), (1, 4)],
    6: [(6, 1), (3, 2), (1, 6), (2, 3)],
    7: [(7, 1), (1, 7)],
    8: [(8, 1), (4, 2), (1, 8), (2, 4)],
    9: [(9, 1), (3, 3), (1, 9)],
    12: [(12, 1), (6, 2), (4, 3), (3, 4), (2, 6), (1, 12)],
}
rects

{2: [(2, 1), (1, 2)],
 4: [(4, 1), (2, 2), (1, 4)],
 6: [(6, 1), (3, 2), (1, 6), (2, 3)],
 7: [(7, 1), (1, 7)],
 8: [(8, 1), (4, 2), (1, 8), (2, 4)],
 9: [(9, 1), (3, 3), (1, 9)],
 12: [(12, 1), (6, 2), (4, 3), (3, 4), (2, 6), (1, 12)]}

In [82]:
offsets = {}
for hh, rr in rects.items():
    for r in rr:
        c1 = list(range(-r[0] + 1, 1))
        c2 = list(range(-r[1] + 1, 1))
        offsets[r] = list(product(c1, c2))
        
offsets

{(2, 1): [(-1, 0), (0, 0)],
 (1, 2): [(0, -1), (0, 0)],
 (4, 1): [(-3, 0), (-2, 0), (-1, 0), (0, 0)],
 (2, 2): [(-1, -1), (-1, 0), (0, -1), (0, 0)],
 (1, 4): [(0, -3), (0, -2), (0, -1), (0, 0)],
 (6, 1): [(-5, 0), (-4, 0), (-3, 0), (-2, 0), (-1, 0), (0, 0)],
 (3, 2): [(-2, -1), (-2, 0), (-1, -1), (-1, 0), (0, -1), (0, 0)],
 (1, 6): [(0, -5), (0, -4), (0, -3), (0, -2), (0, -1), (0, 0)],
 (2, 3): [(-1, -2), (-1, -1), (-1, 0), (0, -2), (0, -1), (0, 0)],
 (7, 1): [(-6, 0), (-5, 0), (-4, 0), (-3, 0), (-2, 0), (-1, 0), (0, 0)],
 (1, 7): [(0, -6), (0, -5), (0, -4), (0, -3), (0, -2), (0, -1), (0, 0)],
 (8, 1): [(-7, 0),
  (-6, 0),
  (-5, 0),
  (-4, 0),
  (-3, 0),
  (-2, 0),
  (-1, 0),
  (0, 0)],
 (4, 2): [(-3, -1),
  (-3, 0),
  (-2, -1),
  (-2, 0),
  (-1, -1),
  (-1, 0),
  (0, -1),
  (0, 0)],
 (1, 8): [(0, -7),
  (0, -6),
  (0, -5),
  (0, -4),
  (0, -3),
  (0, -2),
  (0, -1),
  (0, 0)],
 (2, 4): [(-1, -3),
  (-1, -2),
  (-1, -1),
  (-1, 0),
  (0, -3),
  (0, -2),
  (0, -1),
  (0, 0)],
 (9, 1): 

In [273]:
def build_solutions():
    solutions = {coord: [] for coord in hint_coords}
    for coord in solutions:
        poss = []
        num = puzzle[coord]
        for rect in rects[num]:
            h, w = rect
            for offset in offsets[rect]:
                x0, y0 = np.add(coord, offset)
                x1, y1 = np.add(coord, offset) + [h, w]
                slices = np.s_[x0:x1, y0:y1]
                poss.append(slices)
        solutions[coord] = poss
    return solutions
        
solutions = build_solutions()
solutions

{(0, 2): [(slice(-8, 1, None), slice(2, 3, None)),
  (slice(-7, 2, None), slice(2, 3, None)),
  (slice(-6, 3, None), slice(2, 3, None)),
  (slice(-5, 4, None), slice(2, 3, None)),
  (slice(-4, 5, None), slice(2, 3, None)),
  (slice(-3, 6, None), slice(2, 3, None)),
  (slice(-2, 7, None), slice(2, 3, None)),
  (slice(-1, 8, None), slice(2, 3, None)),
  (slice(0, 9, None), slice(2, 3, None)),
  (slice(-2, 1, None), slice(0, 3, None)),
  (slice(-2, 1, None), slice(1, 4, None)),
  (slice(-2, 1, None), slice(2, 5, None)),
  (slice(-1, 2, None), slice(0, 3, None)),
  (slice(-1, 2, None), slice(1, 4, None)),
  (slice(-1, 2, None), slice(2, 5, None)),
  (slice(0, 3, None), slice(0, 3, None)),
  (slice(0, 3, None), slice(1, 4, None)),
  (slice(0, 3, None), slice(2, 5, None)),
  (slice(0, 1, None), slice(-6, 3, None)),
  (slice(0, 1, None), slice(-5, 4, None)),
  (slice(0, 1, None), slice(-4, 5, None)),
  (slice(0, 1, None), slice(-3, 6, None)),
  (slice(0, 1, None), slice(-2, 7, None)),
  (slic

{(0, 2): [(slice(-8, 1, None), slice(2, 3, None)),
  (slice(-7, 2, None), slice(2, 3, None)),
  (slice(-6, 3, None), slice(2, 3, None)),
  (slice(-5, 4, None), slice(2, 3, None)),
  (slice(-4, 5, None), slice(2, 3, None)),
  (slice(-3, 6, None), slice(2, 3, None)),
  (slice(-2, 7, None), slice(2, 3, None)),
  (slice(-1, 8, None), slice(2, 3, None)),
  (slice(0, 9, None), slice(2, 3, None)),
  (slice(-2, 1, None), slice(0, 3, None)),
  (slice(-2, 1, None), slice(1, 4, None)),
  (slice(-2, 1, None), slice(2, 5, None)),
  (slice(-1, 2, None), slice(0, 3, None)),
  (slice(-1, 2, None), slice(1, 4, None)),
  (slice(-1, 2, None), slice(2, 5, None)),
  (slice(0, 3, None), slice(0, 3, None)),
  (slice(0, 3, None), slice(1, 4, None)),
  (slice(0, 3, None), slice(2, 5, None)),
  (slice(0, 1, None), slice(-6, 3, None)),
  (slice(0, 1, None), slice(-5, 4, None)),
  (slice(0, 1, None), slice(-4, 5, None)),
  (slice(0, 1, None), slice(-3, 6, None)),
  (slice(0, 1, None), slice(-2, 7, None)),
  (slic

### Remove all slices that don't result in a rectangle of *Hint* size

In [397]:
def get_possible_solutions(puzzle, solutions) -> dict:
    """If there are still valid options remaining, returns a new solutions dict."""
    new_solutions = {}
    for hint, slices in solutions.items():
        possible = slices
        possible = [ss for ss in possible if puzzle[ss].size > 0]  # rect must be inside puzzle.
        possible = [ss for ss in possible if (np.isnan(puzzle[ss]) == False).sum() == 1]  # rect must not come in contact with other hints
        if not possible:
            raise ValueError("Given puzzle not possible with current remaining solutions")
        new_solutions[hint] = possible
    return new_solutions
    
    
def decide_next_step(solutions):
    """Randomly picks an option from the smallest-size hint solution pool, returning a Hint and a Slice."""
    solution_lens = [(len(sol), hint) for hint, sol in solutions.items()]
    solution_lens.sort()
    sol, hint = solution_lens[0]
    if sol == 1:
        return hint, solutions[hint][0]
    else:
        return hint, random.choice(solutions[hint])
    
def make_step_inplace(puzzle, solutions, hint, slice):
    if (np.isnan(puzzle[slice]) == False).sum() != 1:
        raise ValueError("Move is not valid.")
    del solutions[hint]
    puzzle[slice] = puzzle[hint]
    
def check_if_solved(puzzle):
    return True if np.isnan(puzzle).sum() == 0 else False
        
    
    

solved = False
while not solved:
    
    puzzle = build_puzzle()
    solutions = build_solutions()
    
    while solutions:
        try:
            solutions = get_possible_solutions(puzzle, solutions)
        except ValueError:
            break
        hint, slice = decide_next_step(solutions)
        make_step_inplace(puzzle, solutions, hint, slice)
        if len(solutions) <= 1:
            print(puzzle, end='\n------------------\n\n')
        if check_if_solved(puzzle):
            solved = True
            break
print(puzzle, end='\n------------------------\n')


[[ 9.  9.  9.      2.  2.      6.  6.  6.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  6.  6.          6.  6.  6.  8.  8.  8.  8.      6.  6.  6.        ]
 [ 9.  9.  9.  6.  6.      7.  7.  7.  7.  7.  7.  7.          6.  6.  6.      4.]
 [ 6.  6.  6.  6.  6.      6.  6.  6.              6.  6.  6.  6.  6.  6.      4.]
 [ 6.  6.  6.         12.  6.  6.  6.  6.  9.         12.  4.              2.  2.]
 [ 6.              9. 12.      4.  4.  6.  9.         12.  4.  8.  8.  8.  8.  8.]
 [ 6.      6.  6.  9.          4.  4.  6.  9.         12.  4.              4.  4.]
 [ 6.      6.  6.  9.  6.  6.          6.  9. 12.     12.  4.  2.  2.            ]
 [ 6.      6.  6.  9.  6.  6.  6.  6.  6.  9.         12.  6.  6.          8.  8.]
 [ 6.              9.  6.  6.  6.  6.  6.  9.         12.  6.  6.  4.  4.  4.  4.]]
------------------

[[ 9.  9.  9.      2.  2.      6.  6.  6.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  6.  6.          6.  6.  6.  8.  8.  8.  8.      6. 

KeyboardInterrupt: 

In [330]:
solutions[hint]

[]