In [79]:
!pip install numpy

In [2]:
import numpy as np


## Multidimensional Arrays with Numpy


Numpy arrays can be multidimensional: they can be squares, cubes, hypercubes, etc!  When choosing datastructures, Arrays are best chosen when all of the values in the structure represent the same variable.

With multidimensional arrays, everything is pretty much the same as the 1-dimensional case, with the addition of a few options for specifiying which order the dimensions should be in, and which dimension an operation should operate on.

In [2]:
x = np.random.randint(1, 10, size=(2, 3, 4))
x.size
x.dtype

dtype('int64')

In [3]:
x = np.arange(12).reshape(3, -1)
x[:2, 2:4]

array([[2, 3],
       [6, 7]])

### Creating Multidimensional Arrays

Most of the array-generation functions have a **shape** or **size** optional argument in them.  If you provide a tuple with a new shape specifying the number of elements along each dimension (e.g. (5, 3) will produce a matrix with 5 rows and 3 columns), it will give you something multidimensional!

```python
>>> data = np.random.randint(1, 10, size=(4, 5))
>>> data
array([[9, 7, 4, 2, 3],
       [3, 6, 7, 4, 8],
       [3, 6, 8, 7, 3],
       [6, 9, 4, 2, 2]])
```

For cases where there is no such option, all arrays have a **reshape()** method that lets you take an existing array and make it more-dimensional.  To simply **flatten** the matrix to a single dimension, you can use the **flatten()** method.

```python
>>> data.reshape(2, 10)
array([[9, 7, 4, 2, 3, 3, 6, 7, 4, 8],
       [3, 6, 8, 7, 3, 6, 9, 4, 2, 2]])

>>> data.flatten()
array([9, 7, 4, 2, 3, 3, 6, 7, 4, 8, 3, 6, 8, 7, 3, 6, 9, 4, 2, 2])
```

Numpy also has some auto-calculation features to make it a bit easier to get the shape you need:

```python
>>> data.reshape(-1, 5)  # -1 tells the reshape() method to calculate the value in that spot
array([[9, 7, 4, 2, 3],
       [3, 6, 7, 4, 8],
       [3, 6, 8, 7, 3],
       [6, 9, 4, 2, 2]])

>>> data.flatten()[np.newaxis, :]  # Makes a 1xN array
>>> data.flatten()[None, :]  # Also Makes a 1xN array
>>> data.flatten()[:, None]  # Makes an Nx1 array
```

And if an array has some extra dimensions you don't care about (like a 32x1x1 array, and you just want a 32 array), you can use the **squeeze()** method to squeeze out those extra dimensions!

Finally, you can find out the shape of a matrix by getting its **shape** attribute.  And to get the total number of elements, check its **size** attribute.

```python
>>> data.shape
(4, 5)

>>> data.size
20
```

**Exercises**

*Example*: Generate a 4 x 5 array of random integers between 10 and 20 using **`np.random.randint`**

In [3]:
np.random.randint(10, 21, size=(4, 5))

array([[20, 18, 19, 20, 13],
       [10, 18, 15, 20, 14],
       [10, 16, 19, 15, 16],
       [17, 12, 14, 18, 20]])

Generate a 3 x 10 array of random integers between 1 and 4 using **`np.random.randint`**

In [4]:
np.random.randint(1, 5, size=(3, 10))

array([[3, 1, 1, 4, 1, 2, 3, 1, 1, 1],
       [2, 3, 2, 4, 3, 3, 2, 3, 1, 2],
       [4, 2, 2, 1, 3, 4, 2, 2, 1, 1]])

Make a flat array with all the values between 0 and 11, and then reshape it into a 3 x 4 matrix using **`array.reshape()`**

In [7]:
# 3x4 array of 0 to 11 
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

...Reshape the previous array into a 4 x 3 matrix...

In [8]:
x.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

...Reshape that array into a 2 x 6 matrix...

In [9]:
x.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

...Then flatten it.

In [10]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Confirm its shape.  Is it the same as its size?

In [15]:
x.shape, x.size

((3, 4), 12)

### Reordering Dimensions

There are many ways to transpose matrices:
  - array.T
  - array.transpose()
  - np.transpose(array)
  - array.swapaxes(0, 1)



**Exercises**
Use each of the four above transpose functions on the following array **x**.

In [4]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [19]:
x.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [20]:
np.transpose(x)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [21]:
x.swapaxes(0, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

**Discussion**: Why might Numpy have so many options for the same transformation?  What's the benefit?

### Aggregating Across Axes

| Function | Method |
| :---  | :--- |
| `np.mean(x, axis=0)` | `x.mean(axis=0)` |
| `np.std(x, axis=0)`  | `x.std(axis=0)`  |
| `np.median(x, axis=0)` | *(No median method)* |

Almost all of the Numpy functions have an **axis** option, which lets you limit the operation to just that axis.  

For example, to get the mean of all columns:

```python
>>> array = np.arange(12).reshape(3, 4)
>>> array.mean(axis=0)
array([4., 5., 6., 7.])
```

And the mean of the rows:

```python
>>> array.mean(axis=1)
array([1.5, 5.5, 9.5])
```

Notice that the number of dimensions goes down by default whenever you aggregate across the axis.  If you'd like to keep the dimensions the same, you can also use the **keepdims=True** option:

```python
>>> array.mean(axis=1, keepdims=True)
array([[1.5],
       [5.5],
       [9.5]])
```

**Exercises**: Try it out for yourself, with the provided array `data`:

In [22]:
np.random.seed(42)
data = np.random.randint(0, 10, size=(5, 3)) * [1, 10, 100]
data

array([[  6,  30, 700],
       [  4,  60, 900],
       [  2,  60, 700],
       [  4,  30, 700],
       [  7,  20, 500]])

*Example*: What is the mean of each column?

In [23]:
data.mean(axis=0)

array([  4.6,  40. , 700. ])

What is the standard deviation of each row?

In [24]:
data.std(axis=1)

array([321.64714967, 409.81730347, 316.25727923, 322.14420511,
       229.3996997 ])

What is the maximum of each column?

In [25]:
data.max(axis=0)

array([  7,  60, 900])

What is the mean of each column's median?

In [26]:
np.median(data, axis=0)

array([  4.,  30., 700.])

## Indexing Exercises

Numpy arrays work the same way as other sequences, but they can have multiple dimensions (rows, columns, etc) over which to index/slice the array.

```python
data = np.array([[0, 1, 2,  3],
                 [4, 5, 6,  7],
                 [8, 9, 10, 11]]
               )
second_row = data[1, :]
third_column = data[:, 2]
```

**Exercises**

Using the example dataset *scores*, select only the described elements from each list:

In [5]:
scores = np.arange(1, 49).reshape(6, 8)
scores

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

**Example:** The first score in the 2nd row:

In [29]:
scores[1, 0]

9

The fourth score in the first row:

In [30]:
scores[0, 3]

4

the second score in the fifth row:

In [7]:
scores[4, 1]

34

The third score in the sixth column:

In [8]:
scores[2, 5]

22

**Example**: The third-through-fifth columns:

In [31]:
scores[:, 2:5]

array([[ 3,  4,  5],
       [11, 12, 13],
       [19, 20, 21],
       [27, 28, 29],
       [35, 36, 37],
       [43, 44, 45]])

The first-through-fourth columns:

In [32]:
scores[:, 0:4]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20],
       [25, 26, 27, 28],
       [33, 34, 35, 36],
       [41, 42, 43, 44]])

The second-through-fourth **rows**:

In [33]:
scores[1:4, :]

array([[ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]])

The fourth row:

In [34]:
scores[3, :]

array([25, 26, 27, 28, 29, 30, 31, 32])

The 2nd through 5th score, in the 6th column:

In [35]:
scores[1:6, 5]

array([14, 22, 30, 38, 46])

**Example:** The rectangle inscribed by scores 19, 22, 35, and 38:

In [39]:
scores[2:5, 2:6]

array([[19, 20, 21, 22],
       [27, 28, 29, 30],
       [35, 36, 37, 38]])

The rectangle inscribed by scores 42, 44, 12, and 10:

*(Reminder: to go to the "end" in a slice, just leave out the end number, like in data[2:])*

In [41]:
scores[1:, 1:4]

array([[10, 11, 12],
       [18, 19, 20],
       [26, 27, 28],
       [34, 35, 36],
       [42, 43, 44]])

##### Setting New Values

For arrays, indexing can also be used to assign a new value.  Let's try it out, using the following pattern:

```python
data[0, :] = 10  # changes all values in the first row to 10
data
```

*Tip*: If you want to keep the original array unchanged, `copy()` it to a new variable and change the new array.

**Exercises**

Use the following array, `scores`, in the exercises below:

In [9]:
scores = np.arange(1, 49).reshape(6, 8)
scores

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

**Example**: Change the 3rd column to all 88s:

In [10]:
new_scores = scores.copy()
new_scores[:, 2] = 10
new_scores

array([[ 1,  2, 10,  4,  5,  6,  7,  8],
       [ 9, 10, 10, 12, 13, 14, 15, 16],
       [17, 18, 10, 20, 21, 22, 23, 24],
       [25, 26, 10, 28, 29, 30, 31, 32],
       [33, 34, 10, 36, 37, 38, 39, 40],
       [41, 42, 10, 44, 45, 46, 47, 48]])

Change the 4th row to 0:

In [11]:
new_scores = scores.copy()
new_scores[3, :] = 0
new_scores

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

Change the 5th-7th columns to -1

In [13]:
new_scores = scores.copy()
new_scores[:, 4:7] = -1
new_scores

array([[ 1,  2,  3,  4, -1, -1, -1,  8],
       [ 9, 10, 11, 12, -1, -1, -1, 16],
       [17, 18, 19, 20, -1, -1, -1, 24],
       [25, 26, 27, 28, -1, -1, -1, 32],
       [33, 34, 35, 36, -1, -1, -1, 40],
       [41, 42, 43, 44, -1, -1, -1, 48]])

Change the last score to 999:

In [14]:
new_scores = scores.copy()
new_scores[-1, -1] = 999
new_scores

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16],
       [ 17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47, 999]])